### ISSUE TITLE
Using Godot api in ECS systems

### ISSUE THREAD

**Issue by jcarlosrc** [GodotECS/godex#101]
**Problem**

It is not clear how we can get the Godot api to work in the ECS context. As an example, using Godot physics api to detect collisions or make physics simulation in a ECS system. I can see there is a Shape3dComponent but It is not clear how it can be used to access the Godot physics api which relies on kinematic, static bodies and other classes. The same applies for other classes and features. Maybe it is about documentation.

**Proposal**

As an idea, I don't know how feasible it is to get Godot scenes registered as components to have the full Godot api available in ECS systems. While adding complex scenes as components is not what ECS is about it could integrate Godot in the ECS paradigm.

**Comment by AndreaCatania** [comment]
Yup, it's not clear because right now there is not a specific way of doing it. There are not `Component`s or `System`s that integrate the `PhysicsServer` in Godex (like for the rendering).

I'm working on adding the physics engine to Godex (fully maintained by Godex) so you will be able to create simulations that are really optimized and convenient to deal with, using ECS. For this reason I didn't add a specific way to deal with the `PhysicsServer` (yet at least).

I think that a way to support the `PhysicsServer` in Godex, like I did for the `RenderingServer`, make sense. I think we need that, because some hybrid projects where the gameplay is Scene based and ECS based: will find that a lot useful.

However, my main plan is to allow an ECS physics to run, because for the game I'm working on my plan is to use only ECS for the gameplay.

----

> As an idea, I don't know how feasible it is to get Godot scenes registered as components to have the full Godot api available in ECS systems. While adding complex scenes as components is not what ECS is about it could integrate Godot in the ECS paradigm.

The idea is that you can have some `_process()` that read and write data to Godex. For example, in Wander the gameplay is fully handled by Godex, but the Character animations are node bases using the `AnimationPlayer` (since there are not ECS animations, yet). So, each frame, my `AnimationPlayer` has a script that extract data from the Godex world. This is dome by using the `DynamicQuery`, here you can see an example:

```gdscript
var query: DynamicQuery = null

func _process(delta: float):
	if query == null:
    		query = DynamicQuery.new()
		query.with_component(ECS.Player, false)
		query.with_component(ECS.Health, false)
		query.with_component(ECS.Shield, false)
		query.maybe_component(ECS.Stunned, false)
		query.maybe_component(ECS.HasBall, false)
		query.maybe_component(ECS.HasWeapon, false)

	# Fetches the above data from the world
	query.begin(ECS.get_active_world())

	while query.is_not_done():
		var health_comp = query.get_component(1)
		var shield_comp = query.get_component(2)
		var stunned_comp = query.get_component(3)
		var has_ball_comp = query.get_component(4)
		var has_weapon_comp = query.get_component(5)

		if stunned_comp != null:
			# Not stunned
			pass
		else:
			# Stunned
			pass

		# etc...

		query.next()

	query.end()
```

In the same way, you can also pass the data. For example, let's suppose you have an `Area` that does damage to the Characters that goes inside.

```gdscript
var query: DynamicQuery = null

func _process(delta: float):
	if query == null:
    		query = DynamicQuery.new()
		query.with_component(ECS.Health, true) # This time it's MUTABLE

	# Fetches the above data from the world
	query.begin(ECS.get_active_world())

	# For each overlapped Character
	for body in $Area.get_overlapping_bodies():
		if body is Character:
			# This extracts the `Entity` node from the Character that entered the Area.
			# Imagine that Character scene is as follows:
			# Character (RigidBody) 
			#  |- CharacterEntity (Entity)
			var entity = body.get_child("CharacterEntity")
			
			# If the `World` has this entity, fetch it.
			if query.has(entity.get_entity_id()):
				# Fetches a specific entity ID. You can think about it like data_array[entity_id]
				query.fetch(entity.get_entity_id())

				# Take the component health
				var health_comp = query.get_component(0)

				# Deal damage to this entity.
				health_comp.health -= 10;

	query.end()
```
This is not the final API and is supposed to evolve, so if you have any idea to improve it, I'm glad to read that. Hope it's clear, anyway let me know if you have other questions.

**Comment by jcarlosrc** [comment]
@AndreaCatania  Thanks for the detailed answer. I have a much clear idea of the current state of the project now and how both "worlds" can be used together.

**Comment by AndreaCatania** [comment]
Thanks for this question, I've added a Wiki page https://github.com/GodotECS/godex/wiki/Godex-and-Godot-communication

**Comment by AndreaCatania** [comment]
I've started to support Bullet physics with Godex. I've created a WIKI page here: https://github.com/GodotECS/godex/wiki/Bullet-Physics-engine
