### ISSUE TITLE
In-editor UX enhancements for systems and resources

### ISSUE THREAD

**Issue by reeseschultz** [GodotECS/godex#15]
I'm proposing three features:

1. A way to remove specific resources added to a world.
2. A way to remove specific systems added to a pipeline.
3. A way to rearrange systems in a pipeline (new to Godex, but I'm assuming the system order is strictly enforced, hence the indexing).

@AndreaCatania, would you prefer a PR, or would you rather implement these yourself? Please let me know if I'm missing something.

**Comment by AndreaCatania** [comment]
A PR is really welcome, and if you have some ideas on how to improve the UI, even better.

I've added the possibility to remove and sort the pipeline systems https://github.com/AndreaCatania/godex/pull/6 https://github.com/AndreaCatania/godex/pull/5
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/8342599/103131895-eecd2480-46a2-11eb-9c66-828a2915b726.gif)
however, it's not intuitive at all and if you have better idea please improve it. I was thinking that probably is better to hide the part that shows the components and the resources, since it's only useful when you have to optimize the pipeline for multi-threading.

> A way to remove specific resources added to a world.

Yes this is missing also, feel free to do a PR.

**Comment by reeseschultz** [comment]
Sounds great. Thanks for the feedback. While we're on the topic, I was also wondering about the `Add System` button.

Totally understand adding systems to worlds, but with Godex you must also use that same button to add components to worlds. I understand components being world-bound if that simplifies things from a technical perspective, although do you think the button name should be changed to `Add System or Component`? I suppose it may also make sense to list components added to a world (but maybe it's already there, and I'm just not seeing it). Do you have any thoughts on that?

**Comment by AndreaCatania** [comment]
You don't need to explicitely add components to a `World`, the component storage is automatically created as soon as you add an entity with such `component` assigned to it.

So, the only thing you need to add are `Systems` and `Resources`. Now that I think about it, we could make the `Resource` creation also automatic, so you just need to compose your pipeline by adding the `System`s. I don't know, what do you think?

**Comment by reeseschultz** [comment]
I see, thanks for clearing that up.

I agree that automatic `Resource` creation is much better from a user perspective. I don't know what a speculative implementation for that would entail, though, as I'm new to Godot and your plugin. Taking baby steps as I transition away from Unity DOTS, so I've got a lot of source code and documentation left to read.

**Comment by AndreaCatania** [comment]
Yes, a null resource doesn't seems useful in any way, I'll add it.

**Comment by AndreaCatania** [comment]
Closed for mistake. The resource are now automatically created: #21

**Comment by AndreaCatania** [comment]
Now the left part is completely void. My initial idea was to account some space to put some World info. Now that `Resource` handling is gone, would make sense make that part smaller to give more room to the pipeline creation.
